image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: 'Build and Test'
        image: composer/composer:1.10.20
        script:
          - /usr/bin/composer install
#          - vendor/bin/phpcs ./src
#          - phpcs ./src
          - vendor/bin/phpcs ./src

  branches:
    master:
       - step:
           name: 'To prod'
           image: composer/composer:1.10.20
           script:
             - /usr/bin/composer install
             - ssh nastbekkerman@143.110.225.69 to_prod.sh